### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by thebadcoder96** [meri-nova/Break-Into-Data-Discord-Bot#7]
Right now we only have one test case that will start the Discord bot and check if it is successfully connected to Discord within 5 seconds.

This isn't ideal because it relies on an arbitrary sleep duration, which can be unreliable cuz what if there are network issues or startup variability? Wdyt?

Also what other test cases should we add? Testing the connection with the database and testing the commands [`/stats` and `/submit`] is what comes to mind rn.

**Comment by KostyaCholak** [comment]
Having tests is an important step that will simplify the process of approving contributor's PRs and it will give them feedback on the problems introduced by the changes. It's essential to always know what we want to be tested. It seems to me that the current test tests that:
- `client.start` is being called
- discord api is working
- network connection is stable enough to get a response within 5s

I'm not sure that we need to test any of that. Tests are almost always isolated from the network (by design) and we never want to test that some external service is working, our concern is to only test our logic. Did I misunderstood the intent behind the test?

Also do you mind if I move the test file from `src` folder to `tests`?

**Comment by thebadcoder96** [comment]
I agree. I had proposed a test case using mocks, specifically `pytest-mock` that will mock the network part so we can test if the bot is connected. Would this be a good approach?

I discussed with @meri-nova a couple of days ago and she wanted to test the network and connections with the database and stuff so we scrapped the proposed test. Come to think of it, I think you are right tho. We should be testing our logic since that is what we have control over and would be affected by our changes. The network is something we do not have that much control over and it makes sense that tests would be isolated from the network.

**Comment by KostyaCholak** [comment]
@thebadcoder96 We definitely will need to use mocking to mock the network calls to discord, database and openai. But when we do it there will be no point in checking that the bot is connected, because now it's just a mock, so it can't fail unless the call to `client.start` is removed. We can test the llm submissions functionality, that's the weakest point right now. I will need to refactor the code a bit before we can test it properly, or you can move the csv parsing part from the main parsing function. That way we can test that different csv data is processed properly (LLMs can output different formats or do random stuff, so we need to be prepared to handle that).

**Comment by thebadcoder96** [comment]
PR: #15
